---
- name: Run Play Book Random Password
  hosts: localhost
  become: yes
  vars_files:
    - list.yml
  tasks:
  - name: Run Play
    vars:
      password: "{{ lookup('password', './passwordfile-{{item.first}} length=6') }}" 
    user:
      name: "{{item.first}}"
      uid: "{{item.uid}}"
      shell: /bin/bash
      comment: "{{item.first|capitalize}} {{item.midd|capitalize}}"
      password: "{{password|password_hash('sha512')}}"
      update_password: on_create
      state: present
    loop: "{{list}}"

